version: "2"

services:
  web:
    image: nginx:alpine
    volumes:
      - ./app:/home/app
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/.ssl:/home/app/.ssl
    ports:
      - ${WEB_PORT}:80
    networks:
      - default
    depends_on:
      - "php-fpm"
    restart: on-failure
    
  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  
  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
      args:
        APP_CONTAINER_USER: ${APP_CONTAINER_USER}
        APP_CONTAINER_UID: ${APP_CONTAINER_UID}
        APP_CONTAINER_GID: ${APP_CONTAINER_GID}
        APP_CONTAINER_VAR_DIR: ${APP_CONTAINER_VAR_DIR}
        APP_CONTAINER_CACHE_DIR: ${APP_CONTAINER_CACHE_DIR}
    volumes:
      - ./app:/home/app
    working_dir: /home/app
    environment:
      PS1: ${PS1}
      PS1_SRV_NAME: php-fpm
      COMPOSE_PROJECT: ${COMPOSE_PROJECT}
      APP_DATA_SOURCE: ${APP_DATA_SOURCE}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      XDEBUG_CONFIG: >-
        idekey=PHPSTORM
        remote_enable=${XDEBUG_REMOTE_ENABLE}
        remote_host=${XDEBUG_REMOTE_HOST}
        remote_port=${XDEBUG_REMOTE_PORT}
        remote_connect_back=0
        remote_autostart=${XDEBUG_REMOTE_AUTOSTART}
        remote_log=/home/app/var/remote.log
        profiler_enable=${XDEBUG_PROFILER_ENABLE}
        profiler_output_dir=/home/app/var
    depends_on:
      - "mysql"
    restart: on-failure
