version: "2"

services:
  web:
    image: nginx:alpine
    volumes:
      - ../app:/home/app
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./.ssl:/home/app/.ssl
    ports:
      - ${WEB_PORT}:80
    environment:
      VIRTUAL_HOST: ${DOMAIN}
    networks:
      - default
    depends_on:
      - "php-fpm"
    restart: on-failure
    
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  
  php-fpm:
    build: 
        context: ./php-fpm
        dockerfile: ./Dockerfile
    volumes:
      - ../app:/home/app
    environment:
      XDEBUG_CONFIG: remote_enable=${XDEBUG_REMOTE_ENABLE} remote_host=${XDEBUG_REMOTE_HOST} remote_port=${XDEBUG_REMOTE_PORT} remote_connect_back=0 remote_autostart=${XDEBUG_REMOTE_AUTOSTART} remote_log=/tmp/remote.log
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    depends_on:
      - "mysql"
    restart: on-failure
